version: '3.3'

services:
    pharmacy-db:
      image: postgres:14.1
      restart: always
      networks:
        - database
      environment:
        POSTGRES_PASSWORD: 1234
        POSTGRES_USER: postgres
        POSTGRES_DB: drugstore
      volumes:
        - type: bind
          source: ./init.sql
          target: /docker-entrypoint-initdb.d/init.sql
      ports:
        - 5432:5432

networks:
    database:
      name: database
      driver: bridge